### ISSUE TITLE
Paper Plotting Tools

### ISSUE THREAD

**Issue by marianogabitto** [theislab/scatac_poisson_reproducibility#1]
Hi Laura,
           would It be possible to ask you if there is any code in the repo to generate the quantitative metrics in the paper?

Thanks,

Mariano

**Comment by lauradmartens** [comment]
Hi Mariano, do you mean plotting the distribution? For that you could see the example notebook and the plotting module. For the integration metrics, I used the plotting tools from [scib](https://github.com/theislab/scib-reproducibility). Specifically the [plotSingleTaskATAC.R](https://github.com/theislab/scib-reproducibility/blob/main/visualization/plotSingleTaskATAC.R) script. I hope that helps!

**Comment by marianogabitto** [comment]
Hi Laura,
           one more question. I got to install and use scib and I can compute the metrics, I failed with plotSingle... even with a simple example. Would it be possible to ask you good point of contacts for both packages to ask them more questions? I do not want to bother you too much.


Thanks,

Mariano
