### ISSUE TITLE
How to save and load model

### ISSUE THREAD

**Issue by wangmhan** [theislab/scatac_poisson_reproducibility#3]
Hi,

Thank you for the effort to develop the module!

I have a question about how to save and load model. I followed the step of example_notebook. 
Because I used a public server, so that need to submit job. I saved the result after model.train(): model.save(dir_path,overwrite=True). 
But I don't find the instruction how to load the model back. Wonder how to do it?

Looking forward to your reply! Thank you.

**Comment by lauradmartens** [comment]
Hi! 

Sorry for the late reply. You can load the model again with `poisson_atac.model.PoissonVI.load(save_path, adata=adata)`. I hope that helps!
