### ISSUE TITLE
to get the imputed fragment count matrix

### ISSUE THREAD

**Issue by wangmhan** [theislab/scatac_poisson_reproducibility#4]
Dear author,

In scvi-tools, it is possible to get the imputed expression matrix as they discussed: https://github.com/scverse/scvi-tools/issues/284. Is it possible to convert poissonVAE model to scvi model, so that can also generate imputed fragment count matrix for scATAC data?
In my case, I have data from different batch but different condition as well. So it could be also interesting to study not only the latent space, but the imputed value.

Thank you so much!

**Comment by lauradmartens** [comment]
Thank you very much for your question. You can get the imputed normalized fragment counts using the function `model.get_accessibility_estimates`. You can provide a total fragment count that you would like to normalize to (e.g just 1 or to the median fragment count number across all cells). Also see `Figure2_cell_type_separation.ipynb` for an example. I hope that helps.
